interface ZIF_I_ZQMPP001_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_ZQMPP001,
 CREATE_ZI_ZQMPP001             TYPE /BOBF/ACT_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9AF821',
 DELETE_ZI_ZQMPP001             TYPE /BOBF/ACT_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9B7821',
 EXECUTAR                       TYPE /BOBF/ACT_KEY VALUE 'ADD8C3ED9D2F1EDDAEA1EBBABF9A766F',
 LOCK_ZI_ZQMPP001               TYPE /BOBF/ACT_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9A3821',
 SAVE_ZI_ZQMPP001               TYPE /BOBF/ACT_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9BF821',
 UNLOCK_ZI_ZQMPP001             TYPE /BOBF/ACT_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9A7821',
 UPDATE_ZI_ZQMPP001             TYPE /BOBF/ACT_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9B3821',
 VALIDATE_ZI_ZQMPP001           TYPE /BOBF/ACT_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9BB821',
      END OF ZI_ZQMPP001,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_ZQMPP001,
        BEGIN OF LOCK_ZI_ZQMPP001,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_ZQMPP001,
        BEGIN OF UNLOCK_ZI_ZQMPP001,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_ZQMPP001,
      END OF ZI_ZQMPP001,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_ZQMPP001,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9A1821',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF99D821',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9AD821',
      END OF ZI_ZQMPP001,
      BEGIN OF ZI_ZQMPP001_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9C5821',
      END OF ZI_ZQMPP001_LOCK,
      BEGIN OF ZI_ZQMPP001_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9C3821',
      END OF ZI_ZQMPP001_MESSAGE,
      BEGIN OF ZI_ZQMPP001_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9C7821',
      END OF ZI_ZQMPP001_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_ZQMPP001,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_ZQMPP001,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C9462FFE3821' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_ZQMPP001' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_ZQMPP001,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'ADD8C3ED9D2F1EEDAE91F90E51FD188B',
 ADMINISTRATIVE_DATA            TYPE /BOBF/DET_KEY VALUE 'ADD8C3ED9D2F1EDDAF88C0668E0CD7EC',
 SET_PROCID                     TYPE /BOBF/DET_KEY VALUE 'ADD8C3ED9D2F1EDDAEA5E138E1B8DE2F',
      END OF ZI_ZQMPP001,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_ZQMPP001                    TYPE /BOBF/OBM_NODE_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF997821',
 ZI_ZQMPP001_LOCK               TYPE /BOBF/OBM_NODE_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF99F821',
 ZI_ZQMPP001_MESSAGE            TYPE /BOBF/OBM_NODE_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF99B821',
 ZI_ZQMPP001_PROPERTY           TYPE /BOBF/OBM_NODE_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF9AB821',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_ZQMPP001,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  PROCID                         TYPE STRING VALUE 'PROCID',
  AUTYP                          TYPE STRING VALUE 'AUTYP',
  GSBER                          TYPE STRING VALUE 'GSBER',
  AUART                          TYPE STRING VALUE 'AUART',
  CCKEY                          TYPE STRING VALUE 'CCKEY',
  PLNBEZ                         TYPE STRING VALUE 'PLNBEZ',
  LTEXT                          TYPE STRING VALUE 'LTEXT',
  DATA_EXECUCAO                  TYPE STRING VALUE 'DATA_EXECUCAO',
  MENGE                          TYPE STRING VALUE 'MENGE',
  MEINS                          TYPE STRING VALUE 'MEINS',
  TIMESTAMP_EXECUCAO             TYPE STRING VALUE 'TIMESTAMP_EXECUCAO',
  ERNAM                          TYPE STRING VALUE 'ERNAM',
  ERDAT                          TYPE STRING VALUE 'ERDAT',
  AENAM                          TYPE STRING VALUE 'AENAM',
  AEDAT                          TYPE STRING VALUE 'AEDAT',
  DATAEXECUCAO                   TYPE STRING VALUE 'DATAEXECUCAO',
  TIMESTAMPEXECUCAO              TYPE STRING VALUE 'TIMESTAMPEXECUCAO',
      END OF ZI_ZQMPP001,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_ZQMPP001,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'ADD8C3ED9D2F1EEDAE91C961EF999821',
      END OF ZI_ZQMPP001,
    END OF SC_NODE_CATEGORY .
endinterface.
